/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Student Editions
         * @description Replace a student's edition enrollments wholesale (a student can be in
         *     several editions -- e.g. retaking a course, or across different courses).
         *     Editions are global (see documents/edition.py), so this only records
         *     *when*, not *which course* -- there is no "set course" endpoint at all;
         *     course association lives on `Rubric`, not on the student/edition pair.
         */
        put: operations["set_student_editions_students__student_id__editions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Students
         * @description Bulk-create/update students from an uploaded roster CSV.
         *
         *     All rows are parsed and validated before anything is written: a single
         *     bad row (missing ID number or First name, or an ID number reused by two
         *     rows in the same file) 422s the whole import instead of leaving a
         *     half-applied roster. An existing student (matched by `student_id`) has
         *     `name`/`username`/`email`/`group` overwritten wholesale with the row's
         *     values -- including clearing a field the row leaves blank -- rather than
         *     merged field by field.
         */
        post: operations["import_students_students_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Editions */
        get: operations["list_editions_editions_get"];
        put?: never;
        /** Create Edition */
        post: operations["create_edition_editions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{edition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edition */
        get: operations["get_edition_editions__edition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rubrics */
        get: operations["list_rubrics_rubrics_get"];
        put?: never;
        /**
         * Create Rubric
         * @description Create a rubric directly from a JSON body -- the "fill a form" path.
         */
        post: operations["create_rubric_rubrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{rubric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rubric */
        get: operations["get_rubric_rubrics__rubric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Rubric Yaml
         * @description Create a rubric from an uploaded YAML file (see README.md for the format).
         */
        post: operations["upload_rubric_yaml_rubrics_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{rubric_id}/test-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Rubric Answer
         * @description Grade one free-typed answer against a single question of this rubric,
         *     synchronously, with no Submission/file/MinIO/Celery involved -- lets a
         *     rubric author try out wording changes and see the LLM's actual response
         *     before wiring up a real exam upload. Nothing here is persisted.
         */
        post: operations["test_rubric_answer_rubrics__rubric_id__test_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_submissions_get"];
        put?: never;
        /** Create Submission */
        post: operations["create_submission_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Submission File */
        get: operations["download_submission_file_submissions__submission_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/regrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regrade Submission
         * @description Force a submission back through extraction+grading from scratch.
         *
         *     `_grade_submission` always re-downloads the raw file, re-extracts answers
         *     (using whichever extractor `rubric.format` selects), and rebuilds
         *     `answers` from the rubric's current questions, so this discards any
         *     previous grades/feedback -- exactly what "force re-grade" should do (e.g.
         *     after fixing a rubric or the uploaded file, or retrying a `failed` run).
         */
        post: operations["regrade_submission_submissions__submission_id__regrade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnsweredQuestion */
        AnsweredQuestion: {
            /** Question Id */
            question_id: string;
            /** Student Answer */
            student_answer: string;
            grade?: components["schemas"]["Grade"] | null;
        };
        /** Body_create_submission_submissions_post */
        Body_create_submission_submissions_post: {
            /** File */
            file: string;
            student_id: components["schemas"]["PydanticObjectId"];
            rubric_id: components["schemas"]["PydanticObjectId"];
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
        };
        /** Body_import_students_students_import_post */
        Body_import_students_students_import_post: {
            /** File */
            file: string;
            format: components["schemas"]["StudentImportFormat"];
        };
        /** Body_upload_rubric_yaml_rubrics_upload_post */
        Body_upload_rubric_yaml_rubrics_upload_post: {
            /** Yaml File */
            yaml_file: string;
            /** Slug */
            slug?: string | null;
            course_id?: components["schemas"]["PydanticObjectId"] | null;
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            format?: components["schemas"]["SubmissionFormat"] | null;
        };
        /**
         * Course
         * @description A subject, e.g. "BDM" -- reused across years. See Edition for a
         *     specific term instance of a course (e.g. "2026/27").
         */
        Course: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CourseCreate */
        CourseCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * Edition
         * @description A term, e.g. "2026/27" -- global, shared across every course taught
         *     that term, not owned by any one of them. Which course(s) an edition
         *     actually applies to is expressed elsewhere, per use: a `Rubric` pins
         *     itself to one course *and* (optionally) one edition (`Rubric.course`/
         *     `.edition`), and a `Student` enrolls directly in editions
         *     (`Student.edition_ids`) -- there is no `Edition.course` here to look
         *     either of those up through. See AGENTS.md's "Data model" section for why
         *     this was pulled out of `Edition` (it used to belong to exactly one
         *     course, which meant "2026/27" had to be recreated once per course and
         *     then looked like two unrelated, identically-named editions everywhere in
         *     the UI).
         */
        Edition: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EditionCreate */
        EditionCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * Grade
         * @description A single graded answer, as stored (`AnsweredQuestion.grade`).
         *
         *     `level` is deliberately a plain `str`, not an `Enum` -- which level
         *     identifiers are valid depends on the owning rubric's `grading_scale`
         *     (arbitrary per-rubric data, not a fixed set known at class-definition
         *     time). Structural validation against a *specific* rubric's scale happens
         *     per grading call instead, via `grade_schema_for_scale` below -- this
         *     class is just the stable shape everything gets normalized back into for
         *     storage, regardless of which scale produced it.
         */
        Grade: {
            /**
             * Level
             * @description Identifier of the assigned grading level (one of the rubric's grading_scale keys).
             */
            level: string;
            /**
             * Feedback
             * @description Short (2-3 sentence), specific feedback addressed to the student: what they got right and, more importantly, what they are missing.
             */
            feedback: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** @example 5eb7cf5a86d9755df3a6c593 */
        PydanticObjectId: string;
        /**
         * Question
         * @description One gradable question: where to read the student's answer from the
         *     submitted file, plus grading instructions.
         *
         *     DB-agnostic on purpose -- reused both as the grading-time input (see
         *     grading.py) and embedded verbatim inside the `Rubric` Beanie document.
         */
        Question: {
            /** Id */
            id: string;
            /** Field */
            field?: string | null;
            /** Title */
            title: string;
            /** Question */
            question: string;
            /** Context */
            context?: string | null;
            /** Rubric */
            rubric: string;
            /** Expected Points */
            expected_points?: string[];
            /** Model Answer */
            model_answer?: string | null;
            /**
             * Needs Python Sandbox
             * @default false
             */
            needs_python_sandbox: boolean;
        };
        /**
         * Rubric
         * @description A gradable deliverable's rubric -- not every deliverable is an exam,
         *     it might be a lab. "Rubric" covers both.
         */
        Rubric: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Course */
            course: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Edition */
            edition?: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            } | null;
            /** @default pdf */
            format: components["schemas"]["SubmissionFormat"];
            /** Grading Scale */
            grading_scale?: {
                [key: string]: string;
            };
            /** Questions */
            questions: components["schemas"]["Question"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** RubricCreate */
        RubricCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug?: string | null;
            course_id: components["schemas"]["PydanticObjectId"];
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            /** @default pdf */
            format: components["schemas"]["SubmissionFormat"];
            /** Grading Scale */
            grading_scale?: {
                [key: string]: string;
            };
            /** Questions */
            questions: components["schemas"]["Question"][];
        };
        /** Student */
        Student: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Student Id */
            student_id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
            /** Group */
            group?: string | null;
            /** Edition Ids */
            edition_ids?: components["schemas"]["PydanticObjectId"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Student Id */
            student_id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
        };
        /** StudentEditions */
        StudentEditions: {
            /** Edition Ids */
            edition_ids: components["schemas"]["PydanticObjectId"][];
        };
        /**
         * StudentImportFormat
         * @description Which roster-export shape an uploaded CSV follows. Only one today
         *     (Atenea, UPC's Moodle instance) -- add a new member plus a matching
         *     `_parse_*` function registered in `_IMPORT_PARSERS` for another, same
         *     shape as `SubmissionFormat`/`_EXTRACTORS` in grading/extraction/.
         * @enum {string}
         */
        StudentImportFormat: "atenea";
        /** StudentImportResult */
        StudentImportResult: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Students */
            students: components["schemas"]["Student"][];
        };
        /**
         * Submission
         * @description A student's deliverable against a rubric -- "correction" was a
         *     confusing name (it reads as "the fix," not "the thing graded"), and not
         *     every rubric is an exam, so "submission" fits both labs and exams.
         */
        Submission: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Student */
            student: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Rubric */
            rubric: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Edition */
            edition: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** File Object Key */
            file_object_key: string;
            /** @default pending */
            status: components["schemas"]["SubmissionStatus"];
            /** Answers */
            answers?: components["schemas"]["AnsweredQuestion"][];
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * SubmissionFormat
         * @description Which file format a rubric's submissions are graded from.
         *
         *     Set once on the `Rubric` (see `documents/rubric.py`), not per
         *     `Submission`: a rubric's `Question.field` values only make sense under
         *     one format (a PDF AcroForm field name vs. a notebook cell tag), so a
         *     rubric authored for one format never accepts the other. Determines two
         *     things: which extractor in `grading/extraction/` turns the raw uploaded
         *     file into `{answer_key: text}`, and how `Question.field` is interpreted
         *     while doing that.
         * @enum {string}
         */
        SubmissionFormat: "pdf" | "notebook";
        /**
         * SubmissionStatus
         * @enum {string}
         */
        SubmissionStatus: "pending" | "extracting" | "grading" | "graded" | "failed";
        /** TestAnswerRequest */
        TestAnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_students_students_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    create_student_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_student_editions_students__student_id__editions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentEditions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_students_students_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_students_students_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    create_course_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_editions_editions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"][];
                };
            };
        };
    };
    create_edition_editions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edition_editions__edition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rubrics_rubrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"][];
                };
            };
        };
    };
    create_rubric_rubrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rubric_rubrics__rubric_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_rubric_yaml_rubrics_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_rubric_yaml_rubrics_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_rubric_answer_rubrics__rubric_id__test_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grade"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_submissions_get: {
        parameters: {
            query?: {
                student_id?: components["schemas"]["PydanticObjectId"] | null;
                rubric_id?: components["schemas"]["PydanticObjectId"] | null;
                course_id?: components["schemas"]["PydanticObjectId"] | null;
                edition_id?: components["schemas"]["PydanticObjectId"] | null;
                status?: components["schemas"]["SubmissionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_submission_submissions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_submission_file_submissions__submission_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regrade_submission_submissions__submission_id__regrade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
