/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Students
         * @description Bulk-create/update students from an uploaded roster CSV.
         *
         *     All rows are parsed and validated before anything is written: a single
         *     bad row (missing ID number or First name, or an ID number reused by two
         *     rows in the same file) 422s the whole import instead of leaving a
         *     half-applied roster. An existing student (matched by `student_id`) has
         *     `name`/`username`/`email` overwritten wholesale with the row's values --
         *     including clearing a field the row leaves blank -- rather than merged
         *     field by field.
         */
        post: operations["import_students_students_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Editions */
        get: operations["list_editions_editions_get"];
        put?: never;
        /** Create Edition */
        post: operations["create_edition_editions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{edition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edition */
        get: operations["get_edition_editions__edition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rubrics
         * @description Optionally filtered by the rubric's own `course`/`edition` links --
         *     unlike `Submission`'s `course_id` filter (api/routers/submissions.py),
         *     no two-step lookup is needed here: `Rubric.course`/`.edition` *are* the
         *     relationship being filtered on, not one derived from another link. Same
         *     `Link.id ==` pattern either way (AGENTS.md sharp edge #3), so a positive
         *     match is only verified against real MongoDB, not mongomock -- see
         *     tests/test_rubrics_api.py's filter tests.
         */
        get: operations["list_rubrics_rubrics_get"];
        put?: never;
        /**
         * Create Rubric
         * @description Create a rubric directly from a JSON body -- the "fill a form" path.
         */
        post: operations["create_rubric_rubrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{rubric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rubric */
        get: operations["get_rubric_rubrics__rubric_id__get"];
        /**
         * Update Rubric
         * @description Edit an existing rubric in place from a JSON body -- the "Build
         *     manually" edit path (same body shape as `POST /rubrics`, see
         *     `RubricCreate`). Unlike creation, a duplicate `slug` only 409s if it
         *     belongs to a *different* rubric -- resubmitting the form unchanged (or
         *     changing everything except the slug) isn't a conflict with itself.
         */
        put: operations["update_rubric_rubrics__rubric_id__put"];
        post?: never;
        /**
         * Delete Rubric
         * @description Delete a rubric outright. Blocked with `409` if any `Submission` or
         *     `Batch` already references it -- deleting out from under those would
         *     leave them pointing at nothing (`Submission.rubric`/`Batch.rubric` are
         *     both required `Link[Rubric]` fields, and every submission/batch view
         *     reads `rubric.slug`/`.title`/`.questions` to render at all), silently
         *     breaking history that already exists rather than just losing an unused
         *     definition. A rubric with no submissions/batches yet (still being
         *     drafted, or never actually used) deletes freely.
         */
        delete: operations["delete_rubric_rubrics__rubric_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Rubric Yaml
         * @description Create a rubric from an uploaded YAML file (see README.md for the format).
         */
        post: operations["upload_rubric_yaml_rubrics_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{rubric_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Rubric Yaml
         * @description Edit an existing rubric in place by uploading a new YAML file -- the
         *     "upload updated version" edit path. Same parsing as `POST
         *     /rubrics/upload`, except:
         *     - the slug (if not overridden by the form field or a `slug:` YAML key)
         *       defaults to the rubric's *current* slug rather than being re-derived
         *       from the uploaded filename -- re-uploading a differently-named file to
         *       update an existing rubric shouldn't change its identity as a side
         *       effect.
         *     - a `course_slug:`/`edition_slug:` key in the file is ignored
         *       (`honor_yaml_course_edition=False`) -- a rubric's course/edition
         *       aren't editable via this flow at all (see `_parse_rubric_yaml`'s
         *       docstring), only via the `course_id`/`edition_id` form fields.
         */
        put: operations["update_rubric_yaml_rubrics__rubric_id__upload_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{rubric_id}/test-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Rubric Answer
         * @description Grade one free-typed answer against a single question of this rubric,
         *     synchronously, with no Submission/file/MinIO/Celery involved -- lets a
         *     rubric author try out wording changes and see the LLM's actual response
         *     before wiring up a real exam upload. Nothing here is persisted.
         */
        post: operations["test_rubric_answer_rubrics__rubric_id__test_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_submissions_get"];
        put?: never;
        /** Create Submission */
        post: operations["create_submission_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Submission Student
         * @description Manually set (or correct) which student a submission belongs to --
         *     mainly for a batch-created submission whose folder name didn't
         *     auto-match anyone, or matched the wrong person (see
         *     api/routers/batches.py's `_match_student`), but works for any
         *     submission.
         */
        put: operations["set_submission_student_submissions__submission_id__student_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Submission File */
        get: operations["download_submission_file_submissions__submission_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/feedback.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Submission Feedback
         * @description Standalone HTML export of this submission's graded feedback -- see
         *     `feedback_export.render_feedback_html`'s docstring for why it's a single
         *     self-contained file rather than e.g. rendering the same page the SPA
         *     does.
         */
        get: operations["download_submission_feedback_submissions__submission_id__feedback_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}/regrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regrade Submission
         * @description Force a submission back through extraction+grading from scratch.
         *
         *     `_grade_submission` always re-downloads the raw file, re-extracts answers
         *     (using whichever extractor `rubric.format` selects), and rebuilds
         *     `answers` from the rubric's current questions, so this discards any
         *     previous grades/feedback -- exactly what "force re-grade" should do (e.g.
         *     after fixing a rubric or the uploaded file, or retrying a `failed` run).
         */
        post: operations["regrade_submission_submissions__submission_id__regrade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}/feedback.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Batch Feedback
         * @description Zip of one standalone feedback HTML per submission in this batch,
         *     each inside a folder named after `Submission.batch_internal_id` -- the
         *     exact per-student folder name from the original upload (see its
         *     docstring). Re-uploading this zip as-is into the originating LMS (e.g.
         *     Moodle/Atenea's "upload multiple feedback files in a zip" for an
         *     assignment) then lines each file back up with the right student, the
         *     same way the LMS's own per-submission export named these folders in the
         *     first place.
         */
        get: operations["download_batch_feedback_batches__batch_id__feedback_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}/regrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regrade Batch
         * @description Force every submission in this batch back through extraction+grading
         *     from scratch -- the bulk version of `POST /submissions/{id}/regrade`
         *     (same per-submission reset: status back to `pending`, `error` cleared,
         *     re-enqueued), for when a whole batch needs re-running (e.g. after fixing
         *     the rubric, or a bad LLM provider config affected the whole run).
         */
        post: operations["regrade_batch_batches__batch_id__regrade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnsweredQuestion */
        AnsweredQuestion: {
            /** Question Id */
            question_id: string;
            /** Student Answer */
            student_answer: string;
            grade?: components["schemas"]["Grade"] | null;
        };
        /**
         * Batch
         * @description One batch-upload event: a zip containing one subfolder per student
         *     submission, all against the same rubric. `rubric` (implying the course,
         *     same as `Submission` never storing course directly) is required; `edition`
         *     is required too, resolved the same way a single submission's edition is
         *     (the rubric's own edition if it has one, else the uploader's explicit
         *     choice). See `Submission.batch`/`.batch_internal_id` for how the
         *     individual extracted items relate back to this.
         */
        Batch: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Rubric */
            rubric: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Edition */
            edition: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            type: components["schemas"]["BatchType"];
            /** Original Filename */
            original_filename?: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** BatchRegradeResult */
        BatchRegradeResult: {
            /** Regraded */
            regraded: number;
        };
        /**
         * BatchType
         * @description Which zip layout a batch upload follows -- only one today (Atenea,
         *     UPC's Moodle instance's assignment-submission export). Same shape as
         *     `StudentImportFormat`/`_IMPORT_PARSERS` in `api/routers/students.py`:
         *     add a member here plus a matching parser registered in
         *     `api/routers/batches.py`'s `_BATCH_PARSERS` for another.
         * @enum {string}
         */
        BatchType: "atenea";
        /** BatchUploadResult */
        BatchUploadResult: {
            batch: components["schemas"]["Batch"];
            /** Created */
            created: number;
            /** Submissions */
            submissions: components["schemas"]["Submission"][];
        };
        /** Body_create_batch_batches_post */
        Body_create_batch_batches_post: {
            /** File */
            file: string;
            rubric_id: components["schemas"]["PydanticObjectId"];
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            type: components["schemas"]["BatchType"];
        };
        /** Body_create_submission_submissions_post */
        Body_create_submission_submissions_post: {
            /** File */
            file: string;
            student_id: components["schemas"]["PydanticObjectId"];
            rubric_id: components["schemas"]["PydanticObjectId"];
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
        };
        /** Body_import_students_students_import_post */
        Body_import_students_students_import_post: {
            /** File */
            file: string;
            format: components["schemas"]["StudentImportFormat"];
        };
        /** Body_update_rubric_yaml_rubrics__rubric_id__upload_put */
        Body_update_rubric_yaml_rubrics__rubric_id__upload_put: {
            /** Yaml File */
            yaml_file: string;
            /** Slug */
            slug?: string | null;
            course_id?: components["schemas"]["PydanticObjectId"] | null;
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            format?: components["schemas"]["SubmissionFormat"] | null;
        };
        /** Body_upload_rubric_yaml_rubrics_upload_post */
        Body_upload_rubric_yaml_rubrics_upload_post: {
            /** Yaml File */
            yaml_file: string;
            /** Slug */
            slug?: string | null;
            course_id?: components["schemas"]["PydanticObjectId"] | null;
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            format?: components["schemas"]["SubmissionFormat"] | null;
        };
        /**
         * Course
         * @description A subject, e.g. "BDM" -- reused across years. See Edition for a
         *     specific term instance of a course (e.g. "2026/27").
         */
        Course: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CourseCreate */
        CourseCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * Edition
         * @description A term, e.g. "2026/27" -- global, shared across every course taught
         *     that term, not owned by any one of them. Which course(s) an edition
         *     actually applies to is expressed elsewhere: a `Rubric` pins itself to
         *     one course *and* (optionally) one edition (`Rubric.course`/`.edition`)
         *     -- there is no `Edition.course` here to look it up through. See
         *     AGENTS.md's "Data model" section for why
         *     this was pulled out of `Edition` (it used to belong to exactly one
         *     course, which meant "2026/27" had to be recreated once per course and
         *     then looked like two unrelated, identically-named editions everywhere in
         *     the UI).
         */
        Edition: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EditionCreate */
        EditionCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * Grade
         * @description A single graded answer, as stored (`AnsweredQuestion.grade`).
         *
         *     `level` is deliberately a plain `str`, not an `Enum` -- which level
         *     identifiers are valid depends on the owning rubric's `grading_scale`
         *     (arbitrary per-rubric data, not a fixed set known at class-definition
         *     time). Structural validation against a *specific* rubric's scale happens
         *     per grading call instead, via `grade_schema_for_scale` below -- this
         *     class is just the stable shape everything gets normalized back into for
         *     storage, regardless of which scale produced it.
         */
        Grade: {
            /**
             * Level
             * @description Identifier of the assigned grading level (one of the rubric's grading_scale keys).
             */
            level: string;
            /**
             * Feedback
             * @description Short (2-3 sentence), specific feedback addressed to the student: what they got right and, more importantly, what they are missing.
             */
            feedback: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** @example 5eb7cf5a86d9755df3a6c593 */
        PydanticObjectId: string;
        /**
         * Question
         * @description One gradable question: where to read the student's answer from the
         *     submitted file, plus grading instructions.
         *
         *     DB-agnostic on purpose -- reused both as the grading-time input (see
         *     grading.py) and embedded verbatim inside the `Rubric` Beanie document.
         */
        Question: {
            /** Id */
            id: string;
            /** Field */
            field?: string | null;
            /** Title */
            title: string;
            /** Question */
            question: string;
            /** Context */
            context?: string | null;
            /** Rubric */
            rubric: string;
            /** Expected Points */
            expected_points?: string[];
            /** Model Answer */
            model_answer?: string | null;
            /**
             * Needs Python Sandbox
             * @default false
             */
            needs_python_sandbox: boolean;
        };
        /**
         * Rubric
         * @description A gradable deliverable's rubric -- not every deliverable is an exam,
         *     it might be a lab. "Rubric" covers both.
         */
        Rubric: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Course */
            course: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Edition */
            edition?: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            } | null;
            /** @default pdf */
            format: components["schemas"]["SubmissionFormat"];
            /** Grading Scale */
            grading_scale?: {
                [key: string]: string;
            };
            /** Questions */
            questions: components["schemas"]["Question"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** RubricCreate */
        RubricCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug?: string | null;
            course_id: components["schemas"]["PydanticObjectId"];
            edition_id?: components["schemas"]["PydanticObjectId"] | null;
            /** @default pdf */
            format: components["schemas"]["SubmissionFormat"];
            /** Grading Scale */
            grading_scale?: {
                [key: string]: string;
            };
            /** Questions */
            questions: components["schemas"]["Question"][];
        };
        /** SetSubmissionStudent */
        SetSubmissionStudent: {
            student_id: components["schemas"]["PydanticObjectId"];
        };
        /** Student */
        Student: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Student Id */
            student_id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Student Id */
            student_id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
        };
        /**
         * StudentImportFormat
         * @description Which roster-export shape an uploaded CSV follows. Only one today
         *     (Atenea, UPC's Moodle instance) -- add a new member plus a matching
         *     `_parse_*` function registered in `_IMPORT_PARSERS` for another, same
         *     shape as `SubmissionFormat`/`_EXTRACTORS` in grading/extraction/.
         * @enum {string}
         */
        StudentImportFormat: "atenea";
        /** StudentImportResult */
        StudentImportResult: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Students */
            students: components["schemas"]["Student"][];
        };
        /**
         * Submission
         * @description A student's deliverable against a rubric -- "correction" was a
         *     confusing name (it reads as "the fix," not "the thing graded"), and not
         *     every rubric is an exam, so "submission" fits both labs and exams.
         *
         *     Normally one per student x rubric -- but a submission created by a batch
         *     upload (see `batch`/`batch_internal_id` below) starts out with no
         *     `student`: the zip's per-item folder name isn't necessarily identifiable
         *     against our roster at upload time, only `rubric`/`edition` are known.
         *     Grading doesn't need `student` at all (see `worker/tasks.py`), so this
         *     doesn't block a batch item from being graded -- only from being
         *     attributed to a specific student until something matches it up later.
         */
        Submission: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /** Student */
            student?: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            } | null;
            /** Rubric */
            rubric: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** Edition */
            edition: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            };
            /** File Object Key */
            file_object_key: string;
            /** @default pending */
            status: components["schemas"]["SubmissionStatus"];
            /** Answers */
            answers?: components["schemas"]["AnsweredQuestion"][];
            /** Error */
            error?: string | null;
            /** Batch */
            batch?: {
                /** Id */
                id: string;
                /** Collection */
                collection: string;
            } | {
                [key: string]: unknown;
            } | null;
            /** Batch Internal Id */
            batch_internal_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * SubmissionFormat
         * @description Which file format a rubric's submissions are graded from.
         *
         *     Set once on the `Rubric` (see `documents/rubric.py`), not per
         *     `Submission`: a rubric's `Question.field` values only make sense under
         *     one format (a PDF AcroForm field name vs. a notebook cell tag), so a
         *     rubric authored for one format never accepts the other. Determines two
         *     things: which extractor in `grading/extraction/` turns the raw uploaded
         *     file into `{answer_key: text}`, and how `Question.field` is interpreted
         *     while doing that.
         * @enum {string}
         */
        SubmissionFormat: "pdf" | "notebook";
        /**
         * SubmissionStatus
         * @enum {string}
         */
        SubmissionStatus: "pending" | "extracting" | "grading" | "graded" | "failed";
        /** TestAnswerRequest */
        TestAnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_students_students_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    create_student_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_students_students_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_students_students_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    create_course_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_editions_editions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"][];
                };
            };
        };
    };
    create_edition_editions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edition_editions__edition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edition_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rubrics_rubrics_get: {
        parameters: {
            query?: {
                course_id?: components["schemas"]["PydanticObjectId"] | null;
                edition_id?: components["schemas"]["PydanticObjectId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rubric_rubrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rubric_rubrics__rubric_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rubric_rubrics__rubric_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rubric_rubrics__rubric_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_rubric_yaml_rubrics_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_rubric_yaml_rubrics_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rubric_yaml_rubrics__rubric_id__upload_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_rubric_yaml_rubrics__rubric_id__upload_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_rubric_answer_rubrics__rubric_id__test_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grade"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_submissions_get: {
        parameters: {
            query?: {
                student_id?: components["schemas"]["PydanticObjectId"] | null;
                rubric_id?: components["schemas"]["PydanticObjectId"] | null;
                course_id?: components["schemas"]["PydanticObjectId"] | null;
                edition_id?: components["schemas"]["PydanticObjectId"] | null;
                batch_id?: components["schemas"]["PydanticObjectId"] | null;
                status?: components["schemas"]["SubmissionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_submission_submissions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_submission_student_submissions__submission_id__student_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSubmissionStudent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_submission_file_submissions__submission_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_submission_feedback_submissions__submission_id__feedback_html_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regrade_submission_submissions__submission_id__regrade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_batches_get: {
        parameters: {
            query?: {
                rubric_id?: components["schemas"]["PydanticObjectId"] | null;
                edition_id?: components["schemas"]["PydanticObjectId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_batch_batches_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_batch_feedback_batches__batch_id__feedback_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regrade_batch_batches__batch_id__regrade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRegradeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
